### ISSUE TITLE
Eve app report error; homekit reported a missing entitlement

### ISSUE THREAD

**Issue by tomsteenbakkers** [luc-ass/homebridge-evohome#29]
First : thanks for the new update. Using the programs is very good enhancement. I have installed the latest version and everything is working 8n the Eve app on the iPhone.  But on the iPad I see the following error: homekit reported a missing entitlement

The iPhone app of eve show the temperature graphs and shows no errors. The iPad reports the error and does not show the temperature graph. 

Both are on the latest version of iOS 11.

**Comment by luc-ass** [comment]
Strange, I'll have a look into it.

**Comment by fredericvl** [comment]
I've had it once too on my iPhone but it was not impacting on any functionality.
Apparently it has something to do with refreshing things on the background by Eve and that's not supported by Homekit: https://stackoverflow.com/questions/45232576/missing-entitlement-for-api-homekit
I think it's a bug in Eve app instead of in this plugin, correct me if I'm wrong.

**Comment by tomsteenbakkers** [comment]
I think the problem solved itself. The Eve app on the iPad has now data to show in the diagram, and the error is now gone. Thanks for the response and I will close this 'issue'.
