### ISSUE TITLE
Graph data is not listing in measurements

### ISSUE THREAD

**Issue by tomsteenbakkers** [luc-ass/homebridge-evohome#34]
Hi,

I have installed the latest version of the plugin. Great improvement!

The only issue I have is that no entries appear in the measurements and therefor the graph is not showing anything. How can I fix this?

**Comment by luc-ass** [comment]
I noticed a somewhat strange behavior that you have to tap the graph and then go back once to make eve load the data. Not sure where the problem comes from.

On a side note: As data is not persistent between restarts and not synced between iOS devices you loose all your data if you restart homebridge without loading data first.

**Comment by rooi** [comment]
The guys from fakegato added persistence to the graphs. I just issued a PR to include this in evohome

**Comment by luc-ass** [comment]
Great!

**Comment by tomsteenbakkers** [comment]
Ok. The graph data takes indeed sometime to load. I need to wait some minutes before all graphs data is loaded.  It looks like it works now 👌😇

**Comment by luc-ass** [comment]
@rooi implemented the latest version of simont77/fakegato-history

merged.
version bumped to v0.4.2.
published to NPM.
